name: Deploy Azure Bicep

on:
  push:
    tags:
      - 'v*'

jobs:
  test-tag-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show tag info
        run: |
          echo "Pipeline partita correttamente"
          echo "Tag ricevuto: $GITHUB_REF_NAME"
          echo "Ref completa: $GITHUB_REF"